# Generated by Django 2.1.1 on 2018-09-12 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canditate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canditate', models.CharField(max_length=200)),
                ('date_registered', models.DateTimeField(verbose_name='date registered')),
                ('votes', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(max_length=250)),
                ('party_registered_no', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='canditate',
            name='registered_party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ballots.Party'),
        ),
    ]
