# Generated by Django 2.1.1 on 2018-09-12 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ballots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canditate', models.CharField(max_length=200)),
                ('date_registered', models.DateTimeField(verbose_name='date registered')),
                ('votes', models.PositiveIntegerField(default=0)),
                ('registered_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ballots.Party')),
            ],
        ),
        migrations.RemoveField(
            model_name='canditate',
            name='registered_party',
        ),
        migrations.DeleteModel(
            name='Canditate',
        ),
    ]
