# Generated by Django 2.1.1 on 2018-09-12 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ballots', '0002_auto_20180912_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='canditate',
            new_name='candidate',
        ),
    ]
