# Generated by Django 2.1.1 on 2018-09-13 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ballots', '0003_auto_20180912_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='registered_party',
            new_name='party',
        ),
    ]
