# Generated by Django 2.1.1 on 2018-09-13 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ballots', '0005_auto_20180913_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='candidate',
        ),
        migrations.AddField(
            model_name='candidate',
            name='party',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ballots.Party'),
        ),
    ]
